services:
  app:
    build: .
    image: fyp_app:v1.1
    container_name: fyp_app
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: fyp_mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: fyp_adminer
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  mysql_data:
    name: fyp_mysql_data
