services:
  app:
    build: .
    image: fyp_app:v1.1
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f -sS --max-time 5 http://127.0.0.1:8000/ || exit 1"]
      # test: ["CMD", "curl", "-f", "-sS", "--max-time", "5", "http://127.0.0.1:8000/"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - mysql
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --spider -q http://localhost:8080 || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s

volumes:
  mysql_data:
    name: fyp_mysql_data
